package es.ugr.smm.internalWindow;

import es.ugr.smm.imagePanel.ImagePanel;

/**
 * jImageInternalWindow representa la ventana de imágenes 
 * que puede almacenar imágenes creadas por un usuario o 
 * capturas generadas de:
 * <ul>
 *  <li>{@link VentanaInternaCamara}</li>  
 *  <li>{@link VentanaInternaJMFPlayer}</li>
 * </ul>
 * Sobre esta clase se pueden aplicar una 
 * multitud de operaciones de imágenes. Esta  clase usa
 * el panel {@link ImagePanel} para manipular imágenes.
 * 
 *
 * @author Jose Colella
 * @version 1.0
 * @see VentanaInternaCamara
 * @see VentanaInternaJMFPlayer
 * @see ImagePanel
 */
public class jImageInternalWindow extends javax.swing.JInternalFrame {

    /**
     * Inicializa una jImageWindow que
     * proporciona la habilidad para dibujar 
     * 
     */
    public jImageInternalWindow() {
        initComponents();
    }

    /**
     * Este constructor toma como parametro la 
     * altura y la anchura de la ventana interna
     * y construye una ventana con esa altura y anchura
     * 
     * @param height La altura de la ventana
     * @param width  La anchura de la ventana
     */
    public jImageInternalWindow(Integer height, Integer width) {
        initSpecialComponent(height, width);
    }

    //Inicializa la ventana interna
    private void initSpecialComponent(Integer height, Integer width) {

        jScrollPane1 = new javax.swing.JScrollPane();
        imagePanel = new es.ugr.smm.imagePanel.ImagePanel(height, width);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Untitled");
        setPreferredSize(new java.awt.Dimension(height, width));
        imagePanel.setPreferredSize(new java.awt.Dimension(height, width));

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
                imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 517, Short.MAX_VALUE));
        imagePanelLayout.setVerticalGroup(
                imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 276, Short.MAX_VALUE));

        jScrollPane1.setViewportView(imagePanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }

    /**El metodo devuelve el panel de dibujos
     * de la ventana interna
     * 
     * @return {@link ImagePanel} el panel de imágenes
     */
    public ImagePanel getImagePanel() {
        return this.imagePanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imagePanel = new es.ugr.smm.imagePanel.ImagePanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(imagePanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private es.ugr.smm.imagePanel.ImagePanel imagePanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
